version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USERNAME: "postgres"
      POSTGRES_PASSWORD: "Postgres2021@"
    ports:
      - "5432:5432"
    networks:
      - postgres-compose-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "kuanto-kusta@next.com"
      PGADMIN_DEFAULT_PASSWORD: "Postgres2021@"
    ports:
      - "8082:8080"
    depends_on:
      - postgres
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge
